[pytest]

markers=
    test: for testing 
    smoke: smoke testing
    regression: regression testing
    negetiveTestcase: negetiveTestcase testcases
    homePage: homepage testcses
    test2: for testing 
    login: login
    datahandling: datahandling
    results: results